theme: minima
title: FlowerLab
decription: FLOWERLAB adalah sebuah website yang memuat konten menganai berbagai bunga dengan berbagai informasinya, terdapat fitur image recognition, dan tempat jual beli bunga