remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: FlowerLab
description: FLOWERLAB adalah sebuah website yang memuat konten menganai berbagai bunga dengan berbagai informasinya, terdapat fitur image recognition, dan tempat jual beli bunga
